
const MODIFIERS = [
// ---------------- FEATS ----------------
{id:'power-attack',name:'Power Attack',category:'feat',source:'Core Rulebook',appliesTo:['attack','damage'],type:'untyped',
 desc:'Trade attack for damage. Penalty/bonus scale with BAB; damage bonus is x1.5 two-handed, not multiplied on a crit (house rule already used elsewhere in this project — vanilla RAW *does* multiply it on a crit; toggle off if your table uses RAW).',
 compute:(ctx)=>{let step=1+Math.floor((Math.max(1,ctx.bab)-1)/4);return {attack:-step,damage:(ctx.hands===2?3:2)*step,note:'-'+step+' atk / +'+((ctx.hands===2?3:2)*step)+' dmg'}}},
{id:'furious-focus',name:'Furious Focus',category:'feat',source:'Advanced Player\'s Guide',appliesTo:['attack'],type:'special',
 desc:'Requires Power Attack. No Power Attack penalty on your FIRST attack of the turn only (handled specially in the summary, not in the flat total below).',
 special:'furious-focus', compute:()=>({attack:0,damage:0,note:'applied to first attack only — see summary'})},
{id:'deadly-aim',name:'Deadly Aim',category:'feat',source:'Core Rulebook',appliesTo:['attack','damage'],type:'untyped',
 desc:'Ranged version of Power Attack. Same BAB-based scaling, no two-handed x1.5.',
 compute:(ctx)=>{let step=1+Math.floor((Math.max(1,ctx.bab)-1)/4);return {attack:-step,damage:2*step,note:'-'+step+' atk / +'+(2*step)+' dmg'}}},
{id:'weapon-focus',name:'Weapon Focus',category:'feat',source:'Core Rulebook',appliesTo:['attack'],type:'untyped',
 desc:'+1 on attack rolls with the selected weapon.',
 compute:()=>({attack:1,damage:0,note:'+1 atk'})},
{id:'greater-weapon-focus',name:'Weapon Focus, Greater',category:'feat',source:'Core Rulebook',appliesTo:['attack'],type:'untyped',
 desc:'Fighter 8th level. +1 more on attack rolls with the selected weapon (stacks with Weapon Focus — separate untyped feat bonus).',
 compute:()=>({attack:1,damage:0,note:'+1 atk'})},
{id:'weapon-specialization',name:'Weapon Specialization',category:'feat',source:'Core Rulebook',appliesTo:['damage'],type:'untyped',
 desc:'Fighter 4th level. +2 damage with the selected weapon.',
 compute:()=>({attack:0,damage:2,note:'+2 dmg'})},
{id:'greater-weapon-specialization',name:'Weapon Specialization, Greater',category:'feat',source:'Core Rulebook',appliesTo:['damage'],type:'untyped',
 desc:'Fighter 12th level. +2 more damage (stacks with Weapon Specialization).',
 compute:()=>({attack:0,damage:2,note:'+2 dmg'})},
{id:'point-blank-shot',name:'Point-Blank Shot',category:'feat',source:'Core Rulebook',appliesTo:['attack','damage'],type:'untyped',
 desc:'+1 attack and damage with ranged weapons, target within 30 ft.',
 compute:()=>({attack:1,damage:1,note:'+1 atk / +1 dmg'})},
{id:'rapid-shot',name:'Rapid Shot',category:'feat',source:'Core Rulebook',appliesTo:['attack'],type:'untyped',
 desc:'-2 on all ranged attacks this turn, in exchange for one extra attack (extra attack not modeled here — add manually to iteratives).',
 compute:()=>({attack:-2,damage:0,note:'-2 atk (all attacks)'})},

// ---------------- SPELLS ----------------
{id:'bless',name:'Bless',category:'spell',source:'Core Rulebook (1st)',appliesTo:['attack'],type:'morale',
 desc:'+1 morale bonus on attack rolls (and vs. fear saves, not modeled here).',
 compute:()=>({attack:1,damage:0,note:'+1 atk (morale)'})},
{id:'divine-favor',name:'Divine Favor',category:'spell',source:'Core Rulebook (1st)',appliesTo:['attack','damage'],type:'luck',
 desc:'+1 luck bonus per 3 caster levels (max +3) on attack and weapon damage rolls.',
 configFields:[{key:'cl',label:'Caster level',type:'number',default:5}],
 compute:(ctx,cfg)=>{let b=Math.min(3,Math.floor((cfg.cl||1)/3));return {attack:b,damage:b,note:'+'+b+' atk / +'+b+' dmg (luck)'}}},
{id:'prayer',name:'Prayer',category:'spell',source:'Core Rulebook (3rd)',appliesTo:['attack','damage'],type:'luck',
 desc:'+1 luck bonus on attack and weapon damage rolls (does not stack with Divine Favor — both are luck).',
 compute:()=>({attack:1,damage:1,note:'+1 atk / +1 dmg (luck)'})},
{id:'haste',name:'Haste',category:'spell',source:'Core Rulebook (3rd)',appliesTo:['attack'],type:'untyped',
 desc:'+1 on attack rolls (untyped). Also grants an extra attack at full BAB on a full attack — add that manually to iteratives.',
 compute:()=>({attack:1,damage:0,note:'+1 atk'})},
{id:'magic-weapon',name:'Magic Weapon',category:'spell',source:'Core Rulebook (1st)',appliesTo:['attack','damage'],type:'enhancement',
 desc:'+1 enhancement bonus to the weapon (does not stack with a weapon that already has an enhancement bonus — same type).',
 compute:()=>({attack:1,damage:1,note:'+1 atk / +1 dmg (enhancement)'})},
{id:'greater-magic-weapon',name:'Magic Weapon, Greater',category:'spell',source:'Core Rulebook (3rd)',appliesTo:['attack','damage'],type:'enhancement',
 desc:'+1 enhancement bonus per 4 caster levels (max +5).',
 configFields:[{key:'cl',label:'Caster level',type:'number',default:8}],
 compute:(ctx,cfg)=>{let b=Math.min(5,Math.max(1,Math.floor((cfg.cl||1)/4)));return {attack:b,damage:b,note:'+'+b+' atk / +'+b+' dmg (enhancement)'}}},

// ---------------- OTHER (class features / combat rules) ----------------
{id:'smite-evil',name:'Smite Evil',category:'other',source:'Paladin class feature',appliesTo:['attack','damage'],type:'untyped',
 desc:'CHA bonus to attack, paladin level to damage vs the smited target (untyped — no named bonus type given in the rules text).',
 configFields:[{key:'palLvl',label:'Paladin level',type:'number',default:7}],
 compute:(ctx,cfg)=>({attack:ctx.cha,damage:cfg.palLvl||0,note:'+'+ctx.cha+' atk / +'+(cfg.palLvl||0)+' dmg (untyped)'})},
{id:'inspire-courage',name:'Inspire Courage (Bardic Performance)',category:'other',source:'Bard class feature',appliesTo:['attack','damage'],type:'competence',
 desc:'+1 competence bonus per 4 bard levels above 1st (min +1) on attack and weapon damage rolls.',
 configFields:[{key:'bardLvl',label:'Bard level',type:'number',default:5}],
 compute:(ctx,cfg)=>{let l=cfg.bardLvl||1,b=l>=17?4:l>=11?3:l>=5?2:1;return {attack:b,damage:b,note:'+'+b+' atk / +'+b+' dmg (competence)'}}},
{id:'charge',name:'Charge',category:'other',source:'Core combat rule',appliesTo:['attack'],type:'untyped',
 desc:'+2 on the attack roll (and -2 AC, not modeled here). One attack only, full-round action.',
 compute:()=>({attack:2,damage:0,note:'+2 atk'})},
{id:'flanking',name:'Flanking',category:'other',source:'Core combat rule',appliesTo:['attack'],type:'untyped',
 desc:'+2 on melee attack rolls when you and an ally threaten opposite sides of the target.',
 compute:()=>({attack:2,damage:0,note:'+2 atk'})},
];
