// Run with: node --test tests/find-your-class-v2-launcher.test.js
// Static HTML coverage for find-your-class-v2/index.html, mirroring the
// static-check style already used for the v1 page (no DOM/jsdom available).
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const pageHtml = fs.readFileSync(path.join(root, 'find-your-class-v2', 'index.html'), 'utf8');
const appJs = fs.readFileSync(path.join(root, 'assets', 'find-your-class', 'v2', 'app.js'), 'utf8');

test('find-your-class-v2/index.html loads the v2 scripts, not the v1 ones', () => {
  assert.match(pageHtml, /src="\.\.\/assets\/find-your-class\/v2\/loader\.js"/);
  assert.match(pageHtml, /src="\.\.\/assets\/find-your-class\/v2\/matcher\.js"/);
  assert.match(pageHtml, /src="\.\.\/assets\/find-your-class\/v2\/narrative\.js"/);
  assert.match(pageHtml, /src="\.\.\/assets\/find-your-class\/v2\/app\.js"/);
  assert.ok(!/src="\.\.\/assets\/find-your-class\/(loader|matcher|concept-parser)\.js"/.test(pageHtml), 'must not accidentally load a v1 script');
});

test('find-your-class-v2/index.html is titled "Classfinder" and loads/passes narrative-questions.json', () => {
  assert.match(pageHtml, /<title>Classfinder<\/title>/);
  assert.match(pageHtml, /getJson\('narrative-questions\.json'\)/);
  assert.match(pageHtml, /narrativeDoc: narrativeDoc/);
});

test('find-your-class-v2/index.html resolves all class profiles and archetype batches into one profile set at bootstrap', () => {
  for (let i = 1; i <= 6; i++) assert.match(pageHtml, new RegExp(`class-profiles-batch-0${i}\\.json`));
  for (let i = 1; i <= 10; i++) assert.match(pageHtml, new RegExp(`archetype-profiles-pilot-${String(i).padStart(2, '0')}\\.json`));
  assert.match(pageHtml, /archetype-profiles-slayer\.json/);
  assert.match(pageHtml, /archetype-profiles-summoner-unchained\.json/);
  assert.match(pageHtml, /archetype-profiles-alchemist\.json/);
  for (const id of ['antipaladin','arcanist','barbarian','bard','bloodrager','brawler','cavalier','cleric','druid','fighter','gunslinger','hunter','inquisitor','investigator','kineticist','magus','medium','mesmerist','monk','monk-unchained','ninja','occultist','oracle','paladin','psychic','ranger','rogue','samurai','shaman','shifter','skald','sorcerer','spiritualist','summoner','swashbuckler','vigilante','warpriest','witch','wizard']) assert.match(pageHtml, new RegExp(`archetype-profiles-${id}\\.json`));
  assert.match(pageHtml, /prestige-profiles\.json/);
  assert.match(pageHtml, /resolveAllProfiles\(classProfiles, archetypeOverrides, prestigeProfiles\.profiles\)/);
});

test('find-your-class-v2/index.html has no fixed-width element wider than a 320px viewport', () => {
  const styleBlock = pageHtml.match(/<style>([\s\S]*?)<\/style>/)[1];
  const fixedWidthPx = [...styleBlock.matchAll(/(?<![\w-])width:\s*(\d+)px/g)].map(m => Number(m[1]));
  for (const w of fixedWidthPx) assert.ok(w <= 320, `found a fixed pixel width of ${w}px, which would overflow a 320px viewport`);
});

test('no non-English UI text in the v2 experience', () => {
  const suspiciousChars = /[áéíóúñ¿¡]/i;
  assert.ok(!suspiciousChars.test(pageHtml));
  assert.ok(!suspiciousChars.test(appJs));
});

// Regression: the old free-text "idea" stage captured text but never fed it
// into structured preferences at all (a dead end -- clicking "See results
// for my idea" always matched against zero active preferences). The
// narrative Question mode replaced it by construction (every option carries
// a real preference mutation), so there must be no open free-text input or
// leftover "idea"/"choose-idea" reachable from the choice screen any more.
test('the old dead-end free-text "idea" stage is gone -- no open textarea or choose-idea action remains reachable', () => {
  assert.ok(!/data-action="choose-idea"/.test(appJs));
  assert.ok(!/data-action="set-idea"/.test(appJs));
  assert.ok(!/data-action="apply-idea"/.test(appJs));
  assert.ok(!/fycTextarea/.test(appJs), 'the free-text textarea markup must not still be generated by app.js');
  assert.match(appJs, /data-action="choose-question"/);
  assert.match(appJs, /data-action="question-answer"/);
});

// Regression: wireEvents() originally fell through to the 'click' listener
// for any element that wasn't a TEXTAREA or INPUT -- silently including
// <select> (the search-bar dropdown). A <select>'s value change never fires
// 'click' in a way that reads the new value, so switching searches via the
// dropdown did nothing until this was fixed to also treat SELECT as a
// 'change'-listening element, same as INPUT.
test('wireEvents attaches a "change" listener to SELECT elements, not "click" (the search-bar dropdown regression)', () => {
  const wireEventsSrc = appJs.slice(appJs.indexOf('function wireEvents('), appJs.indexOf('function reRunLastSearchIfShowingResults('));
  assert.match(wireEventsSrc, /SELECT/, 'wireEvents must special-case SELECT elements');
  assert.match(wireEventsSrc, /'SELECT'[^;]*\?\s*'change'/, 'a SELECT element must be wired to the "change" event, not "click"');
});
